spring:
  config:
    name: configserver
  profiles:
    include: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo
server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: '*'
